services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - springboot-mysql-network
  mysqldb:
    image: mysql:8.0.39
    ports:
    - 3307:3306
    expose:
      - 3307
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - LANG=C.UTF-8
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s
#  ldapo:
#    image: osixia/openldap:1.5.0
#    container_name: ldapo
#    environment:
#        - LDAP_ORGANISATION=fhce
#        - LDAP_DOMAIN=fhce.edu.uy
#        - "LDAP_BASE_DN=dc=fhce,dc=edu,dc=uy"
#        - LDAP_ADMIN_PASSWORD=password
#    ports:
#        - 389:389
#        - 636:636
#    networks:
#      - springboot-mysql-network
volumes:
  mysql-data:
networks:
  springboot-mysql-network:
    name: springboot-mysql-network
